// src/main/webapp/app/entities/orden/orden-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './orden.reducer';

export const OrdenDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const ordenEntity = useAppSelector(state => state.orden.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="ordenDetailsHeading">
          <Translate contentKey="programacion2FinalApp.orden.detail.title">Orden</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{ordenEntity.id}</dd>
          <dt>
            <span id="cliente">
              <Translate contentKey="programacion2FinalApp.orden.cliente">Cliente</Translate>
            </span>
          </dt>
          <dd>{ordenEntity.cliente}</dd>
          <dt>
            <span id="accionId">
              <Translate contentKey="programacion2FinalApp.orden.accionId">Accion Id</Translate>
            </span>
          </dt>
          <dd>{ordenEntity.accionId}</dd>
          <dt>
            <span id="accion">
              <Translate contentKey="programacion2FinalApp.orden.accion">Accion</Translate>
            </span>
          </dt>
          <dd>{ordenEntity.accion}</dd>
          <dt>
            <span id="operacion">
              <Translate contentKey="programacion2FinalApp.orden.operacion">Operacion</Translate>
            </span>
          </dt>
          <dd>{ordenEntity.operacion}</dd>
          <dt>
            <span id="precio">
              <Translate contentKey="programacion2FinalApp.orden.precio">Precio</Translate>
            </span>
          </dt>
          <dd>{ordenEntity.precio}</dd>
          <dt>
            <span id="cantidad">
              <Translate contentKey="programacion2FinalApp.orden.cantidad">Cantidad</Translate>
            </span>
          </dt>
          <dd>{ordenEntity.cantidad}</dd>
          <dt>
            <span id="fechaOperacion">
              <Translate contentKey="programacion2FinalApp.orden.fechaOperacion">Fecha Operacion</Translate>
            </span>
          </dt>
          <dd>
            {ordenEntity.fechaOperacion ? <TextFormat value={ordenEntity.fechaOperacion} type="date" format={APP_DATE_FORMAT} /> : null}
          </dd>
          <dt>
            <span id="modo">
              <Translate contentKey="programacion2FinalApp.orden.modo">Modo</Translate>
            </span>
          </dt>
          <dd>{ordenEntity.modo}</dd>
        </dl>
        <Button tag={Link} to="/orden" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/orden/${ordenEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default OrdenDetail;

// src/main/webapp/app/entities/orden/detail/orden-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IOrden } from '../orden.model';

@Component({
  selector: 'jhi-orden-detail',
  templateUrl: './orden-detail.component.html',
})
export class OrdenDetailComponent implements OnInit {
  orden: IOrden | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ orden }) => {
      this.orden = orden;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="orden">
      <h2 data-cy="ordenDetailsHeading"><span jhiTranslate="procesadorOrdenApp.orden.detail.title">Orden</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ orden.id }}</span>
        </dd>
        <dt><span jhiTranslate="procesadorOrdenApp.orden.cliente">Cliente</span></dt>
        <dd>
          <span>{{ orden.cliente }}</span>
        </dd>
        <dt><span jhiTranslate="procesadorOrdenApp.orden.accionId">Accion Id</span></dt>
        <dd>
          <span>{{ orden.accionId }}</span>
        </dd>
        <dt><span jhiTranslate="procesadorOrdenApp.orden.accion">Accion</span></dt>
        <dd>
          <span>{{ orden.accion }}</span>
        </dd>
        <dt><span jhiTranslate="procesadorOrdenApp.orden.precio">Precio</span></dt>
        <dd>
          <span>{{ orden.precio }}</span>
        </dd>
        <dt><span jhiTranslate="procesadorOrdenApp.orden.cantidad">Cantidad</span></dt>
        <dd>
          <span>{{ orden.cantidad }}</span>
        </dd>
        <dt><span jhiTranslate="procesadorOrdenApp.orden.fechaOperacion">Fecha Operacion</span></dt>
        <dd>
          <span>{{ orden.fechaOperacion | formatMediumDatetime }}</span>
        </dd>
        <dt><span jhiTranslate="procesadorOrdenApp.orden.modo">Modo</span></dt>
        <dd>
          <span>{{ orden.modo }}</span>
        </dd>
        <dt><span jhiTranslate="procesadorOrdenApp.orden.operacion">Operacion</span></dt>
        <dd>
          <div *ngIf="orden.operacion">
            <a [routerLink]="['/operacion', orden.operacion.id, 'view']">{{ orden.operacion.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Volver</span>
      </button>

      <button type="button" [routerLink]="['/orden', orden.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Editar</span>
      </button>
    </div>
  </div>
</div>
